#!/usr/bin/env node
'use strict';

// Generate the checked-in views of the ordered sentinel-slot registry.
// The registry is the only place where slot identity, defaults, and built-in
// path globs are declared. Module triggers and triage remain runtime-owned.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..', '..');
const REGISTRY_REL = 'scripts/lib/sentinel-slots.json';

const FILES = [
  {
    rel: 'scripts/hooks/_lib/payload.sh',
    key: 'payload',
    begin: '# BEGIN GENERATED sentinel-slots:payload',
    end: '# END GENERATED sentinel-slots:payload',
    render: renderPayloadBlock,
  },
  {
    rel: 'scripts/hooks/post-edit-remind.sh',
    key: 'route',
    begin: '# BEGIN GENERATED sentinel-slots:route',
    end: '# END GENERATED sentinel-slots:route',
    render: renderRouteBlock,
  },
  {
    rel: 'rules/execution-policy.md',
    key: 'agent-table',
    begin: '<!-- BEGIN GENERATED sentinel-slots:agent-table -->',
    end: '<!-- END GENERATED sentinel-slots:agent-table -->',
    render: renderAgentTable,
  },
  {
    rel: 'rules/execution-policy.md',
    key: 'sentinel-table',
    begin: '<!-- BEGIN GENERATED sentinel-slots:sentinel-table -->',
    end: '<!-- END GENERATED sentinel-slots:sentinel-table -->',
    render: renderSentinelTable,
  },
];

function loadRegistry(root = ROOT) {
  const registry = JSON.parse(fs.readFileSync(path.join(root, REGISTRY_REL), 'utf8'));
  if (registry.schema !== 'dhpk.sentinel-slots.v1' || !Array.isArray(registry.slots)) {
    throw new Error(`invalid sentinel registry schema in ${REGISTRY_REL}`);
  }
  if (registry.slots.some((slot) => !slot.id || !slot.name || !slot.label || !slot.short_name)) {
    throw new Error(`sentinel registry contains an incomplete slot in ${REGISTRY_REL}`);
  }
  return registry;
}

function bashArray(values) {
  return `(${values.map((value) => `"${value}"`).join(' ')})`;
}

function renderPayloadBlock(registry) {
  const slots = registry.slots;
  return [
    '# BEGIN GENERATED sentinel-slots:payload',
    '# Generated by scripts/ci/gen-slots.js from scripts/lib/sentinel-slots.json.',
    '# Slot order is a compatibility contract: consumers index these arrays together.',
    `# Review sentinel slots: ${slots.map((slot, i) => `${i}=${slot.id}`).join(' ')}`,
    `SENTINEL_NAMES=${bashArray(slots.map((slot) => slot.name))}`,
    `SENTINEL_LABELS=${bashArray(slots.map((slot) => slot.label))}`,
    `SENTINEL_SHORT_NAMES=${bashArray(slots.map((slot) => slot.short_name))}`,
    `# Default agent names — overridable via userConfig.review_agents (comma-joined).`,
    `_dhpk_default_agents=${bashArray(slots.map((slot) => slot.default_agent))}`,
    '# END GENERATED sentinel-slots:payload',
  ].join('\n');
}

function renderCase(variable, patterns, index) {
  if (!patterns || patterns.length === 0) return [];
  return [
    `    case "${variable}" in`,
    `        ${patterns.join('|')})`,
    `            NEEDS[${index}]=1 ;;`,
    '    esac',
  ];
}

function renderRouteBlock(registry) {
  const lines = [
    '# BEGIN GENERATED sentinel-slots:route',
    '# Generated by scripts/ci/gen-slots.js from scripts/lib/sentinel-slots.json.',
    '# This view owns built-in path routing only; module and user-extension triggers stay below.',
    'dhpk_route_slot() {',
    '    local _rel="$1" _basename="$2"',
  ];
  registry.slots.forEach((slot, index) => {
    const triggers = slot.triggers || {};
    lines.push(...renderCase('$_basename', triggers.basename_globs || [], index));
    lines.push(...renderCase('$_rel', triggers.path_globs || [], index));
    if ((triggers.plugin_source_globs || []).length > 0) {
      lines.push('    if [ -f "$ROOT/.claude-plugin/plugin.json" ]; then');
      lines.push(...renderCase('$_rel', triggers.plugin_source_globs, index).map((line) => `    ${line}`));
      lines.push('    fi');
    }
  });
  lines.push('}', 'dhpk_route_slot "$REL" "$BASENAME"', '# END GENERATED sentinel-slots:route');
  return lines.join('\n');
}

function renderAgentTable(registry) {
  return [
    '<!-- BEGIN GENERATED sentinel-slots:agent-table -->',
    '<!-- Generated by scripts/ci/gen-slots.js from scripts/lib/sentinel-slots.json. -->',
    ...registry.slots.map((slot) => `| \`${slot.label}\` | ${slot.agent_summary} | ${slot.dispatch} |`),
    '<!-- END GENERATED sentinel-slots:agent-table -->',
  ].join('\n');
}

function renderSentinelTable(registry) {
  return [
    '<!-- BEGIN GENERATED sentinel-slots:sentinel-table -->',
    '<!-- Generated by scripts/ci/gen-slots.js from scripts/lib/sentinel-slots.json. -->',
    ...registry.slots.map((slot) => `| \`${slot.name}\` | \`${slot.default_agent}\` | ${slot.trigger_summary} |`),
    '<!-- END GENERATED sentinel-slots:sentinel-table -->',
  ].join('\n');
}

function replaceMarkedBlock(text, spec, rendered) {
  const start = text.indexOf(spec.begin);
  const finish = text.indexOf(spec.end);
  if (start < 0 || finish < 0 || finish < start) return { text, missing: true, stale: false };
  const end = finish + spec.end.length;
  const current = text.slice(start, end);
  if (current === rendered) return { text, missing: false, stale: false };
  return { text: text.slice(0, start) + rendered + text.slice(end), missing: false, stale: true };
}

function checkGeneratedFiles(root = ROOT) {
  const registry = loadRegistry(root);
  const stale = [];
  const missing = [];
  const grouped = new Map();
  for (const spec of FILES) {
    if (!grouped.has(spec.rel)) grouped.set(spec.rel, []);
    grouped.get(spec.rel).push(spec);
  }
  for (const [rel, specs] of grouped) {
    const fp = path.join(root, rel);
    if (!fs.existsSync(fp)) {
      missing.push(rel);
      continue;
    }
    const text = fs.readFileSync(fp, 'utf8');
    for (const spec of specs) {
      const result = replaceMarkedBlock(text, spec, spec.render(registry));
      if (result.missing) missing.push(`${rel}#${spec.key}`);
      else if (result.stale) stale.push(`${rel}#${spec.key}`);
    }
  }
  return { stale, missing };
}

function writeGeneratedFiles(root = ROOT) {
  const registry = loadRegistry(root);
  const changed = [];
  const missing = [];
  const grouped = new Map();
  for (const spec of FILES) {
    if (!grouped.has(spec.rel)) grouped.set(spec.rel, []);
    grouped.get(spec.rel).push(spec);
  }
  for (const [rel, specs] of grouped) {
    const fp = path.join(root, rel);
    if (!fs.existsSync(fp)) { missing.push(rel); continue; }
    let text = fs.readFileSync(fp, 'utf8');
    for (const spec of specs) {
      const result = replaceMarkedBlock(text, spec, spec.render(registry));
      if (result.missing) missing.push(`${rel}#${spec.key}`);
      else if (result.stale) { text = result.text; }
    }
    if (text !== fs.readFileSync(fp, 'utf8')) {
      fs.writeFileSync(fp, text);
      changed.push(rel);
    }
  }
  return { changed, missing };
}

function main(argv = process.argv.slice(2)) {
  const root = ROOT;
  if (argv.includes('--write')) {
    const result = writeGeneratedFiles(root);
    if (result.missing.length) {
      console.error(`FAIL [gen-slots]: missing generated markers: ${result.missing.join(', ')}`);
      return 1;
    }
    console.log(`PASS [gen-slots]: updated ${result.changed.length} file(s).`);
    return 0;
  }
  const result = checkGeneratedFiles(root);
  if (result.missing.length || result.stale.length) {
    if (result.missing.length) console.error(`MISSING [gen-slots]: ${result.missing.join(', ')}`);
    if (result.stale.length) console.error(`STALE [gen-slots]: ${result.stale.join(', ')}`);
    return 1;
  }
  console.log('PASS [gen-slots]: generated views are current.');
  return 0;
}

module.exports = {
  loadRegistry,
  renderPayloadBlock,
  renderRouteBlock,
  renderAgentTable,
  renderSentinelTable,
  checkGeneratedFiles,
  writeGeneratedFiles,
  main,
};

if (require.main === module) process.exit(main());
