#!/usr/bin/env bash
# post-edit-remind.sh — PostToolUse (Edit|Write|MultiEdit) hook
#
# Writes review sentinels based on:
#   1. Built-in file-extension defaults (language-agnostic)
#   2. Active modules' triggers (modules/<name>/module.yaml, set by session-start)
#   3. userConfig.review_trigger_extra_paths (slot-prefixed: code:, db:, sec:, fe:, doc:, mig:)
#
# Sentinels live at $ROOT/.claude/artifacts/sessions/.pending-{review,db-review,security-review,frontend-review,doc-review,polyfill-review,migration-review}
# and are cleared by each review agent's Closing hook via clear-sentinel.sh.
#
# Self-edits to .claude/artifacts/** are skipped (review agents writing their
# own reports would otherwise re-trigger themselves).

set -o pipefail

. "$(dirname "$0")/_lib/session-env.sh"
. "$(dirname "$0")/_lib/payload.sh"

ROOT="$(dhpk_root)"
PAYLOAD="$(dhpk_read_payload)"
FILE_PATH="$(extract_tool_input file_path "$PAYLOAD")"
# Some tool payload variants carry camelCase keys — fall back before giving up.
[ -z "$FILE_PATH" ] && FILE_PATH="$(extract_tool_input filePath "$PAYLOAD")"
[ -z "$FILE_PATH" ] && exit 0

# Containment (D4.1): only arm sentinels for paths inside the project ROOT.
# `${FILE_PATH#$ROOT/}` is a silent no-op when FILE_PATH is not under ROOT — an
# out-of-project absolute path (e.g. a /private/tmp scratchpad file) would pass
# through unchanged and still match an extension rule. Validate containment first.
case "$FILE_PATH" in
    "$ROOT"/*) REL="${FILE_PATH#$ROOT/}" ;;
    /*)  exit 0 ;;                # absolute path outside ROOT — never arm a sentinel
    *)   REL="$FILE_PATH" ;;      # already project-relative — treat as in-project
esac
BASENAME="${REL##*/}"

case "$REL" in
    .claude/artifacts/*) exit 0 ;;
esac

ARTIFACTS="$(dhpk_sessions_dir "$ROOT")"
mkdir -p "$ARTIFACTS"

# The dispatcher normally exports DHPK_ACTIVE_MODULES after SessionStart; the
# normalized fallback also keeps direct hook invocations project-aware.
DHPK_ACTIVE_MODULES="${DHPK_ACTIVE_MODULES:-$(dhpk_config_modules)}"

# Provenance (D4.3): originating OpenSpec change slug (if this edit is inside an
# openspec/changes/<slug>/ tree) else the session id, for later staleness
# detection. Written to the sidecar (not the sentinel line) so field-3 readers
# are unaffected.
#
# Field 4 additionally carries the originating session unconditionally. Field 3
# alone cannot answer "who armed this?" for OpenSpec edits — it holds the change
# slug there — which left the most common review surface unattributable to a
# session, so concurrent sessions could not tell each other's doc-review entries
# apart. Appended rather than substituted: field 3 keeps its slug semantics for
# reap-stale-sentinels.sh's archived-change staleness probe.
_prov="${REL#openspec/changes/}"
_sid="$(extract_top_field session_id "$PAYLOAD")"
PROVENANCE_SESSION="session:${_sid:-unknown}"
if [ "$_prov" != "$REL" ]; then
    _prov="${_prov%%/*}"
    if [ "$_prov" = "archive" ]; then _prov="${REL#openspec/changes/archive/}"; _prov="${_prov%%/*}"; fi
    PROVENANCE="$_prov"
else
    PROVENANCE="$PROVENANCE_SESSION"
fi
PROV_FILE="$ARTIFACTS/$SENTINEL_PROVENANCE_FILE"

NEEDS=(0 0 0 0 0 0 0)

# BEGIN GENERATED sentinel-slots:route
# Generated by scripts/ci/gen-slots.js from scripts/lib/sentinel-slots.json.
# This view owns built-in path routing only; module and user-extension triggers stay below.
dhpk_route_slot() {
    local _rel="$1" _basename="$2"
    case "$_basename" in
        *.php|*.js|*.ts|*.tsx|*.jsx|*.mjs|*.cjs|*.vue|*.svelte|*.py|*.rb|*.go|*.rs|*.java|*.kt|*.swift|*.cs|*.c|*.cpp|*.h|*.hpp)
            NEEDS[0]=1 ;;
    esac
    case "$_rel" in
        .claude/agents/*.sh|.claude/agents/*.json|.claude/agents/*.yml|.claude/agents/*.yaml|.claude/rules/*.sh|.claude/rules/*.json|.claude/rules/*.yml|.claude/rules/*.yaml|.claude/commands/*.sh|.claude/commands/*.json|.claude/commands/*.yml|.claude/commands/*.yaml|.claude/hooks/*.sh|.claude/hooks/*.json|.claude/hooks/*.yml|.claude/hooks/*.yaml|.claude/scripts/*.sh|.claude/scripts/*.json|.claude/scripts/*.yml|.claude/scripts/*.yaml|.claude/skills/*.sh|.claude/skills/*.json|.claude/skills/*.yml|.claude/skills/*.yaml|.claude/manifests/*.sh|.claude/manifests/*.json|.claude/manifests/*.yml|.claude/manifests/*.yaml)
            NEEDS[0]=1 ;;
    esac
    case "$_basename" in
        *.sql)
            NEEDS[1]=1 ;;
    esac
    case "$_rel" in
        *migrations/*.php|*migrations/*.py|*migrations/*.rb|*migrations/*.ts|*migrations/*.js|*migrations/*.sql|*migration/*.php|*migration/*.py|*migration/*.rb|*migration/*.ts|*migration/*.js|*migration/*.sql)
            NEEDS[1]=1 ;;
    esac
    case "$_basename" in
        *Auth*.php|*Auth*.js|*Auth*.ts|*Auth*.tsx|*Auth*.jsx|*Auth*.py|*Auth*.rb|*Auth*.go|*Auth*.rs|*Auth*.java|*auth*.php|*auth*.js|*auth*.ts|*auth*.tsx|*auth*.jsx|*auth*.py|*auth*.rb|*auth*.go|*auth*.rs|*auth*.java|*Login*.php|*Login*.js|*Login*.ts|*Login*.tsx|*Login*.jsx|*Login*.py|*Login*.rb|*Login*.go|*Login*.rs|*Login*.java|*login*.php|*login*.js|*login*.ts|*login*.tsx|*login*.jsx|*login*.py|*login*.rb|*login*.go|*login*.rs|*login*.java|*Acl*.php|*Acl*.js|*Acl*.ts|*Acl*.tsx|*Acl*.jsx|*Acl*.py|*Acl*.rb|*Acl*.go|*Acl*.rs|*Acl*.java|*acl*.php|*acl*.js|*acl*.ts|*acl*.tsx|*acl*.jsx|*acl*.py|*acl*.rb|*acl*.go|*acl*.rs|*acl*.java|*Upload*.php|*Upload*.js|*Upload*.ts|*Upload*.tsx|*Upload*.jsx|*Upload*.py|*Upload*.rb|*Upload*.go|*Upload*.rs|*Upload*.java|*upload*.php|*upload*.js|*upload*.ts|*upload*.tsx|*upload*.jsx|*upload*.py|*upload*.rb|*upload*.go|*upload*.rs|*upload*.java|*File*.php|*File*.js|*File*.ts|*File*.tsx|*File*.jsx|*File*.py|*File*.rb|*File*.go|*File*.rs|*File*.java|*file*.php|*file*.js|*file*.ts|*file*.tsx|*file*.jsx|*file*.py|*file*.rb|*file*.go|*file*.rs|*file*.java)
            NEEDS[2]=1 ;;
    esac
    case "$_basename" in
        CLAUDE.md|AGENTS.md)
            NEEDS[4]=1 ;;
    esac
    case "$_rel" in
        .claude/agents/*.md|.claude/rules/*.md|.claude/commands/*.md|.claude/hooks/*.md|.claude/scripts/*.md|.claude/skills/*.md|.claude/manifests/*.md|openspec/*.md|docs/*.md|README*.md)
            NEEDS[4]=1 ;;
    esac
    if [ -f "$ROOT/.claude-plugin/plugin.json" ]; then
        case "$_rel" in
            agents/*.md|rules/*.md|skills/*.md|agent-traps/*.md|commands/*.md)
                NEEDS[4]=1 ;;
        esac
    fi
}
dhpk_route_slot "$REL" "$BASENAME"
# END GENERATED sentinel-slots:route


# ---- Active-module triggers ----
# DHPK_ACTIVE_MODULES is set by session-start.sh (csv of module names).
# Each module's module.yaml triggers contribute extra extensions and paths per slot.

_dhpk_check_module_triggers() {
    local module_name="$1" module_root="$2"
    [ -f "$module_root/module.yaml" ] || return 0
    command -v python3 >/dev/null 2>&1 || return 0
    # Emit `slot=<0|1|2> kind=<ext|path> value=<v>` lines.
    python3 - "$module_root/module.yaml" "$REL" "$BASENAME" <<'PY' 2>/dev/null
import sys, os, re
def parse_yaml(text):
    # Minimal YAML parser for our flat module.yaml structure:
    #   triggers:
    #     code:
    #       extensions: [".php"]
    #       paths: [protected/, infrastructure/]
    out = {}
    stack = [(0, out)]
    cur_key = None
    for raw in text.splitlines():
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        while stack and indent < stack[-1][0]:
            stack.pop()
        parent = stack[-1][1]
        s = line.strip()
        if ":" in s:
            k, _, v = s.partition(":")
            k = k.strip(); v = v.strip()
            if v == "":
                d = {}
                parent[k] = d
                stack.append((indent + 2, d))
            elif v.startswith("[") and v.endswith("]"):
                inner = v[1:-1].strip()
                items = [x.strip().strip('"').strip("'") for x in inner.split(",") if x.strip()] if inner else []
                parent[k] = items
            else:
                parent[k] = v.strip('"').strip("'")
    return out

path = sys.argv[1]; rel = sys.argv[2]; basename = sys.argv[3]
try:
    with open(path) as f:
        cfg = parse_yaml(f.read())
except Exception:
    sys.exit(0)
triggers = cfg.get("triggers") or {}
# Aliases: "fe" → 3, "frontend" → 3; "doc" → 4; "mig" → 6, "migration" → 6
slot_map = {"code": 0, "db": 1, "sec": 2, "frontend": 3, "fe": 3, "doc": 4, "polyfill": 5, "mig": 6, "migration": 6}
for slot_name, slot_idx in slot_map.items():
    block = triggers.get(slot_name) or {}
    for ext in (block.get("extensions") or []):
        if basename.endswith(ext):
            print(f"{slot_idx}")
            break
    for path_prefix in (block.get("paths") or []):
        if rel.startswith(path_prefix):
            print(f"{slot_idx}")
            break
PY
}

if [ -n "${DHPK_ACTIVE_MODULES:-}" ]; then
    if ! command -v python3 >/dev/null 2>&1; then
        echo "[post-edit] WARN: modules enabled (${DHPK_ACTIVE_MODULES}) but python3 missing — module triggers disabled. Install python3 to enable per-module path triggers." >&2
    else
        PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
        IFS=',' read -r -a _mods <<< "$DHPK_ACTIVE_MODULES"
        for _m in "${_mods[@]}"; do
            _m="$(echo "$_m" | xargs)"  # trim
            [ -z "$_m" ] && continue
            _mdir="$PLUGIN_ROOT/modules/$_m"
            [ -d "$_mdir" ] || continue
            while IFS= read -r _slot; do
                [ -n "$_slot" ] && NEEDS[$_slot]=1
            done < <(_dhpk_check_module_triggers "$_m" "$_mdir")
        done
    fi
fi

# ---- User-supplied extra paths (CLAUDE_PLUGIN_OPTION_REVIEW_TRIGGER_EXTRA_PATHS) ----
# Entries shaped `<slot>:<prefix>` where slot ∈ code|db|sec|fe|doc|mig.
_review_trigger_extra_paths="$(dhpk_config_csv review_trigger_extra_paths '')"
if [ -n "$_review_trigger_extra_paths" ]; then
    IFS=',' read -r -a _extras <<< "$_review_trigger_extra_paths"
    for _e in "${_extras[@]}"; do
        _e="$(echo "$_e" | xargs)"
        case "$_e" in
            code:*) [[ "$REL" == "${_e#code:}"* ]] && NEEDS[0]=1 ;;
            db:*)   [[ "$REL" == "${_e#db:}"* ]] && NEEDS[1]=1 ;;
            sec:*)  [[ "$REL" == "${_e#sec:}"* ]] && NEEDS[2]=1 ;;
            fe:*)   [[ "$REL" == "${_e#fe:}"* ]] && NEEDS[3]=1 ;;
            doc:*)  [[ "$REL" == "${_e#doc:}"* ]] && NEEDS[4]=1 ;;
            mig:*)  [[ "$REL" == "${_e#mig:}"* ]] && NEEDS[6]=1 ;;
        esac
    done
fi

# ---- Triage: drop mechanically-trivial false-positive sentinels ----
# The AI-orchestration triage (execution-policy) makes the judgment calls with
# full diff visibility; this hook-level pass drops sentinels only for the two
# change classes that are *mechanically* safe to detect at write time:
# comment-only edits (drops db/sec/fe/poly/mig; KEEPS code + doc) and small
# pure-style CSS tweaks (net<=8; drops db/sec/fe; keeps code). Whitespace /
# reformatting is intentionally NOT handled here — no git whitespace flag can
# tell inert reindentation from a meaningful string-literal whitespace change
# (e.g. explode('  ') -> explode(' ')), so that judgment is left to the
# orchestration triage. Anything ambiguous (new file, binary, untracked, any
# git uncertainty) KEEPS every sentinel — a missed review is worse than an
# extra one. Diff is measured cumulatively vs HEAD, so a file that grows
# substantial across edits re-acquires its sentinel.
_tri_drop() {  # $1=slot $2=reason — clear NEEDS + remove any pending line for $REL
    local _s="$1"
    [ "${NEEDS[$_s]:-0}" -eq 1 ] || return 0
    NEEDS[$_s]=0
    local _sf="$ARTIFACTS/${SENTINEL_NAMES[$_s]}" _keep
    if [ -f "$_sf" ]; then
        _keep="$(REL_FOR_AWK="$REL" awk 'BEGIN{p=ENVIRON["REL_FOR_AWK"]} { n=$0; sub(/^[^ ]+ [^ ]+ /,"",n); if (n != p) print $0 }' "$_sf" 2>/dev/null)"
        if [ -n "$_keep" ]; then printf '%s\n' "$_keep" > "$_sf"; else rm -f "$_sf"; fi
    fi
    echo "[post-edit] triage-drop ${SENTINEL_SHORT_NAMES[$_s]} ($REL): $2"
    _tri_bump_drop_count "$_s"
}
# Issue #79: count repeated triage-drops of the same slot within one session.
# A slot dropped 2+ times is a recurring false-positive — surface it ONCE with a
# file-a-bug hint instead of silently re-dropping the same mis-scoped trigger
# (session 82bfa020 dropped the same slot 4× before anyone root-caused it).
_tri_bump_drop_count() {
    local _s="$1" _cf="$ARTIFACTS/.triage-drop-counts" _short="${SENTINEL_SHORT_NAMES[$_s]}" _cur _cnt _tmp
    _cur="$(awk -F '\t' -v s="$_short" '$1==s{print $2; exit}' "$_cf" 2>/dev/null || true)"
    _cnt=$(( ${_cur:-0} + 1 ))
    _tmp="$(mktemp 2>/dev/null || printf '%s.tmp.%s' "$_cf" "$$")"
    [ -f "$_cf" ] && awk -F '\t' -v s="$_short" '$1!=s' "$_cf" 2>/dev/null > "$_tmp" || true
    printf '%s\t%s\n' "$_short" "$_cnt" >> "$_tmp"
    mv -f "$_tmp" "$_cf" 2>/dev/null || rm -f "$_tmp"
    if [ "$_cnt" -ge 2 ]; then
        echo "[post-edit] NOTE: '$_short' triage-dropped ${_cnt}x this session — a recurring false-positive suggests a mis-scoped trigger. Consider filing a bug or narrowing it (sentinel-slots.json / module triggers / review_trigger_extra_paths)."
    fi
}
_tri_comment_only() {  # 0 iff >=1 changed line seen and every changed non-blank line is a comment in this file's language
    local _body _ln _t _seen=0 _ext
    _ext="$(printf '%s' "${BASENAME##*.}" | tr '[:upper:]' '[:lower:]')"
    _body="$(git -C "$ROOT" diff HEAD -U0 -- "$REL" 2>/dev/null)" || return 1
    [ -n "$_body" ] || return 1
    while IFS= read -r _ln; do
        case "$_ln" in
            +++*|---*) continue ;;
            +*|-*) _t="${_ln:1}" ;;
            *) continue ;;
        esac
        _t="${_t#"${_t%%[![:space:]]*}"}"   # ltrim
        [ -z "$_t" ] && continue
        _seen=1
        # Unambiguous C-family / markup comment markers (safe at line start in any language).
        case "$_t" in
            '//'*|'/*'*|'* '*|'*/'*|'<!--'*|'-->'*) continue ;;
        esac
        # '#': comment in shell/python/ruby/yaml/php, but id-selector / hex colour in CSS.
        case "$_ext" in
            css|scss|sass|less) ;;
            *) case "$_t" in '#'*) continue ;; esac ;;
        esac
        # '--': line comment only in SQL/Lua, and only as '-- ' or bare '--'
        # (NOT '--$var' pre-decrement, NOT '--custom-prop' CSS custom property).
        case "$_ext" in
            sql|lua) case "$_t" in '-- '*|'--') continue ;; esac ;;
        esac
        return 1   # a non-comment content line → not comment-only
    done <<< "$_body"
    [ "$_seen" -eq 1 ]
}
_tri_checkbox_only() {  # 0 iff this edit is (or, absent per-edit payload, the
    # cumulative diff shows) only checkbox flips.
    #
    # D5 primary path: when the hook's stdin payload carries the Edit tool's
    # own old_string/new_string pair, classify THAT delta directly — it answers
    # the right question ("is THIS edit bookkeeping") instead of the cumulative
    # diff's wrong one ("has this file changed non-trivially since HEAD").
    # Cumulative prose from an earlier, independent edit must not prevent a
    # later, unrelated flip from dropping the sentinel — that earlier edit
    # already armed its own review when it happened. A mixed single edit
    # (flip + prose in one old/new pair) canonicalizes unequal and correctly
    # keeps the sentinel armed.
    #
    # Fallback (Write, MultiEdit fan-out, heredoc — no old/new pair in the
    # payload): the pre-existing cumulative `git diff HEAD` cancellation check.
    # A pure flip means: after canonicalizing the checkbox mark ([x]->[ ]), the
    # set of added lines equals the set of removed lines (they cancel). Adding or
    # removing a task, or a prose edit, leaves an uncancelled line → not a flip,
    # so the doc gate stays armed (matches the spec: only bookkeeping flips exempt).
    [ "$BASENAME" = "tasks.md" ] || return 1
    local _old _new _old_canon _new_canon
    _old="$(extract_tool_input old_string "$PAYLOAD")"
    _new="$(extract_tool_input new_string "$PAYLOAD")"
    if [ -n "$_old" ]; then
        _TRI_CB_MODE=edit
        _old_canon="$(printf '%s' "$_old" | sed -E 's/^([[:space:]]*- \[)[xX](\])/\1 \2/')"
        _new_canon="$(printf '%s' "$_new" | sed -E 's/^([[:space:]]*- \[)[xX](\])/\1 \2/')"
        [ "$_old_canon" = "$_new_canon" ]
        return $?
    fi
    _TRI_CB_MODE=cumulative
    local _body _ln _t _canon _added="" _removed=""
    _body="$(git -C "$ROOT" diff HEAD -U0 -- "$REL" 2>/dev/null)" || return 1
    [ -n "$_body" ] || return 1
    while IFS= read -r _ln; do
        case "$_ln" in
            +++*|---*) continue ;;
            +*|-*) _t="${_ln:1}" ;;
            *) continue ;;
        esac
        [ -z "${_t//[[:space:]]/}" ] && continue   # skip blank changed lines
        # Canonicalize a checkbox mark so a flip cancels; prose lines pass through.
        _canon="$(printf '%s' "$_t" | sed -E 's/^([[:space:]]*- \[)[xX](\])/\1 \2/')"
        case "$_ln" in
            +*) _added="${_added}${_canon}"$'\n' ;;
            -*) _removed="${_removed}${_canon}"$'\n' ;;
        esac
    done <<< "$_body"
    [ -n "${_added}${_removed}" ] || return 1
    [ "$(printf '%s' "$_added" | LC_ALL=C sort)" = "$(printf '%s' "$_removed" | LC_ALL=C sort)" ]
}
_tri_numstat="$(git -C "$ROOT" diff HEAD --numstat -- "$REL" 2>/dev/null | awk 'NR==1{print $1" "$2}')"
_tri_add="${_tri_numstat%% *}"; _tri_rem="${_tri_numstat##* }"
if [ -n "$_tri_numstat" ] && [ "$_tri_add" != "-" ] && [ "$_tri_rem" != "-" ] \
   && printf '%s' "$_tri_add$_tri_rem" | grep -qE '^[0-9]+$'; then
    _tri_net=$(( _tri_add + _tri_rem ))
    _tri_ext="$(printf '%s' "${BASENAME##*.}" | tr '[:upper:]' '[:lower:]')"
    if _tri_comment_only; then
        for _tri_s in 1 2 3 5 6; do _tri_drop "$_tri_s" "comment-only edit"; done
    elif [ "$_tri_net" -le 8 ]; then
        case "$_tri_ext" in
            css|scss|sass|less) for _tri_s in 1 2 3; do _tri_drop "$_tri_s" "pure-style CSS (net=$_tri_net)"; done ;;
        esac
    fi
    # Checkbox-only tasks.md flip: the orchestrator's own progress bookkeeping,
    # never an auditable doc change. Drop the doc slot (the one slot the comment-only
    # pass deliberately keeps) — independent of the comment/CSS branches above.
    #
    # Mode matters here: the per-edit path (_TRI_CB_MODE=edit) only classifies
    # THIS edit's own old/new delta — it says nothing about whether an earlier,
    # independent prose edit to the same file already armed the doc sentinel.
    # Removing that sentinel line via _tri_drop would silently erase review debt
    # that isn't this edit's to clear. So the per-edit path only SUPPRESSES
    # arming for this edit (NEEDS[4]=0, no sentinel-file mutation); only the
    # cumulative fallback path (_TRI_CB_MODE=cumulative, whole-file diff since
    # HEAD nets to pure flips) may safely _tri_drop, since in that case the
    # entire delta really is bookkeeping and removal is correct.
    if _tri_checkbox_only; then
        if [ "$_TRI_CB_MODE" = "edit" ]; then
            NEEDS[4]=0
            echo "[post-edit] triage-suppress doc-review ($REL): checkbox-only tasks.md edit"
        else
            _tri_drop 4 "checkbox-only tasks.md edit"
        fi
    fi
fi

# ---- Orchestration state dotfiles: never owe a doc-review ----
# Leading-dot .md files under openspec/ (e.g. .resume-note.md,
# .hard-rule-escalation.md that an unattended opsx-apply-goal session writes as
# its own bookkeeping) are session state, not auditable spec artifacts — a
# doc-review is never owed for them, and arming one re-churns the doc sentinel
# on every write. Suppress only the doc slot (4), AFTER all built-in +
# config-driven routing, so a project that has explicitly opted a non-doc slot
# into openspec/ (review_trigger_extra_paths / module.yaml paths) still arms it.
case "$REL" in
    openspec/*)
        case "$BASENAME" in .*.md) NEEDS[4]=0 ;; esac ;;
esac

# ---- Write sentinels ----
# Keep the sidecar aligned with the sentinel set observed before this edit. This
# records an externally cleared set before a later edit re-arms it.
ADVISORY_STATE="$ARTIFACTS/.advisory-state"
armed_before="$(find "$ARTIFACTS" -maxdepth 1 -type f -name '.pending-*' -exec basename {} \; 2>/dev/null | LC_ALL=C sort)"
stored_signature=""
[ -f "$ADVISORY_STATE" ] && stored_signature="$(cat "$ADVISORY_STATE")"
if [ "$armed_before" != "$stored_signature" ]; then
    printf '%s\n' "$armed_before" > "$ADVISORY_STATE"
    stored_signature="$armed_before"
fi

# Idempotent append: if $REL already appears in the sentinel (any timestamp),
# skip the write. Stops repeated edits to the same file from accumulating
# duplicate lines that mislead reviewers and stop-review-reminder's `wc -l`.
msg=""
for i in "${!NEEDS[@]}"; do
    if [ "${NEEDS[$i]}" -eq 1 ]; then
        sentinel="$ARTIFACTS/${SENTINEL_NAMES[$i]}"
        # cut -d' ' -f3- drops the "YYYY-MM-DD HH:MM:SS " timestamp prefix,
        # leaving only the path part for an exact-line compare against $REL.
        if [ -f "$sentinel" ] && cut -d' ' -f3- "$sentinel" 2>/dev/null | grep -Fxq -- "$REL"; then
            continue
        fi
        # Line format "<date> <time> <path>" — path at field 3 (see _lib/payload.sh).
        printf '%s %s\n' "$(date +'%Y-%m-%d %H:%M:%S')" "$REL" >> "$sentinel"
        printf '%s\t%s\t%s\t%s\n' "${SENTINEL_NAMES[$i]}" "$REL" "$PROVENANCE" "$PROVENANCE_SESSION" >> "$PROV_FILE"
        msg+=" ${SENTINEL_LABELS[$i]}"
    fi
done

if [ -z "$msg" ]; then
    [ "${DHPK_DEBUG:-0}" = "1" ] && echo "[post-edit] skipped (no trigger matched): $REL"
else
    echo "[post-edit] marked:$msg ($REL)"
    armed_after="$(find "$ARTIFACTS" -maxdepth 1 -type f -name '.pending-*' -exec basename {} \; 2>/dev/null | LC_ALL=C sort)"
    if [ "$armed_after" != "$stored_signature" ]; then
        # D8: run the pending reviewer BEFORE attempting commit/push — a sentinel
        # armed here is review debt, not a suggestion.
        echo "[post-edit] advisory: run the pending reviewer BEFORE attempting commit/push."
        printf '%s\n' "$armed_after" > "$ADVISORY_STATE"
    fi
fi

exit 0
