#!/usr/bin/env bash
# pre-edit-guard.sh — PreToolUse (Edit|Write|MultiEdit) hook
# Block edits to sensitive paths. Exit code 2 = reject the tool call.
#
# Always blocked:
#   - .env / .env.* (secrets)
#   - .git/ directory (git internals)
#   - lock files (composer.lock / package-lock.json / yarn.lock / pnpm-lock.yaml /
#     Cargo.lock / poetry.lock / Pipfile.lock) — must be regenerated by the
#     package manager, never hand-edited
#
# Project-extensible:
#   Set GUARD_EXTRA_PATTERNS to add patterns (pipe-separated grep -E regex).
#   Example: GUARD_EXTRA_PATTERNS="src/locales/.*\.json$|generated/.*"
#   WARNING: used as a grep regex. Only set in trusted project config.

set -euo pipefail

. "$(dirname "$0")/_lib/payload.sh"

stdin_data="$(cat 2>/dev/null || true)"
file_path="$(extract_tool_input file_path "$stdin_data")"

[ -z "$file_path" ] && exit 0

# Block paths with shell metacharacters that enable injection.
if [[ "$file_path" =~ [\;\&\|\`] ]] || [[ "$file_path" =~ \$\( ]]; then
    echo "[edit-guard] rejected suspicious file path (shell metacharacters)" >&2
    exit 2
fi

# Block sensitive paths.
# Exception: .env.example / .env.sample / .env.dist / .env.template are
# version-controlled templates carrying NO secrets — allow editing them.
# (POSIX ERE has no negative lookahead, so carve the exception explicitly.)
if echo "$file_path" | grep -Eq '\.env\.(example|sample|dist|template)$'; then
    :  # allow version-controlled env templates
elif echo "$file_path" | grep -Eq '(\.env(\..*)?$|\.git/)'; then
    echo "[edit-guard] blocked sensitive file: $file_path" >&2
    exit 2
fi

# Block package-manager lock files. Lock files must be regenerated by their
# tool (composer update, npm install, etc.), never hand-edited. Match basename
# so 'project/composer.lock' and 'composer.lock' both trip.
if echo "$file_path" | grep -Eq '(^|/)(composer\.lock|package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|poetry\.lock|Pipfile\.lock|Gemfile\.lock|go\.sum)$'; then
    echo "[edit-guard] blocked lock file: $file_path (regenerate via the package manager, do not hand-edit)" >&2
    exit 2
fi

# Config-protection: block edits that WEAKEN an existing linter / formatter /
# static-analysis config to make a failing gate pass. First-time creation is
# allowed (file does not exist yet); modifying an existing one is blocked to
# steer the agent toward fixing the code, not relaxing the rule.
# Scope is deliberately narrow (pure lint/format/static-analysis configs) to
# avoid false-positives — multi-purpose files like tsconfig.json / package.json
# are intentionally NOT listed (legitimate edits are common).
# Opt out for a session: DHPK_PROTECT_LINT_CONFIGS=0
if [ "${DHPK_PROTECT_LINT_CONFIGS:-1}" != "0" ] && [ -f "$file_path" ]; then
    # basename match — applies at all depths (monorepo sub-package configs included).
    case "$(basename "$file_path")" in
        .eslintrc|.eslintrc.js|.eslintrc.cjs|.eslintrc.json|.eslintrc.yml|.eslintrc.yaml|\
        eslint.config.js|eslint.config.mjs|eslint.config.cjs|eslint.config.ts|eslint.config.mts|eslint.config.cts|\
        .prettierrc|.prettierrc.js|.prettierrc.cjs|.prettierrc.json|.prettierrc.yml|.prettierrc.yaml|prettier.config.js|prettier.config.cjs|prettier.config.mjs|\
        biome.json|biome.jsonc|\
        .php-cs-fixer.php|.php-cs-fixer.dist.php|phpcs.xml|phpcs.xml.dist|phpstan.neon|phpstan.neon.dist|psalm.xml|psalm.xml.dist|\
        .ruff.toml|ruff.toml|.flake8|.pylintrc|mypy.ini|.mypy.ini)
            echo "[edit-guard] blocked lint/formatter config edit: $file_path" >&2
            echo "[edit-guard] Fix the code to satisfy the rule — don't weaken the gate. To change policy intentionally, edit outside Claude or set DHPK_PROTECT_LINT_CONFIGS=0 for this session." >&2
            exit 2 ;;
    esac
fi

# Project-supplied extra patterns.
if [ -n "${GUARD_EXTRA_PATTERNS:-}" ]; then
    # Validate the regex before applying — avoid grep's exit 2 on bad regex blowing up the hook.
    if echo "" | grep -Eq "$GUARD_EXTRA_PATTERNS" 2>/dev/null || [ $? -le 1 ]; then
        if echo "$file_path" | grep -Eq "$GUARD_EXTRA_PATTERNS"; then
            echo "[edit-guard] blocked by GUARD_EXTRA_PATTERNS: $file_path" >&2
            exit 2
        fi
    else
        # Fail closed: a broken regex means the guard is silently OFF for every
        # edit — block instead so the misconfiguration gets fixed, not ignored.
        echo "[edit-guard] blocked: invalid GUARD_EXTRA_PATTERNS regex — fix the pattern (pipe-separated grep -E) or unset it" >&2
        exit 2
    fi
fi

exit 0
